# This file was automatically generated on Mon 21 Sep 2020 15:38:28 BST from
# source: /dls_sw/work/R3.14.12.7/support/BL45P-BUILDER/etc/makeIocs/BL45P-EA-IOC-02.xml
#
# *** Please do not edit this file: edit the source file instead. ***
#

# GK Containers Testing April 2021
# builder built IOCs can be converted to containers by dropping their DB and
# startup script in the config folder of the helm chart
#
# changes to boot script required
#    rename to ioc.boot
#    replace all hardcoded root folder with '$(TOP)' (no quotes)
#    replace references to dbLoadRecords to pass '$(THIS_DIR)/dbname)' (but use double quotes)
#    replace dbLoadDatabase param with dbd/ioc.dbd
#    replace BL45P_MO_IOC_01_registerRecordDeviceDriver with ioc_registerRecordDeviceDriver

cd "$(TOP)"

epicsEnvSet "EPICS_CA_MAX_ARRAY_BYTES", '6000000'
epicsEnvSet "EPICS_TS_MIN_WEST", '0'


# Loading libraries
# -----------------

# Device initialisation
# ---------------------

cd "$(TOP)"

dbLoadDatabase "dbd/ioc.dbd"
ioc_registerRecordDeviceDriver(pdbbase)

drvAsynIPPortConfigure("PANDA01.DRV_CTRL", "172.23.59.50:8888", 100, 0, 0)

drvAsynIPPortConfigure("PANDA01.DRV_DATA", "172.23.59.50:8889", 100, 0, 0)

# Create driver
ADPandABlocksConfig("PANDA01.DRV", "172.23.59.50", 100000, 1000, 0, 0)

drvAsynIPPortConfigure("PANDA02.DRV_CTRL", "172.23.59.51:8888", 100, 0, 0)

drvAsynIPPortConfigure("PANDA02.DRV_DATA", "172.23.59.51:8889", 100, 0, 0)

# Create driver
ADPandABlocksConfig("PANDA02.DRV", "172.23.59.51", 100000, 1000, 0, 0)

# NDPosPluginConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize)
NDPosPluginConfigure("PANDA01.POS", 1000, 0, "PANDA01.DRV", 0, 0, 0, 0, 0)

# NDPosPluginConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxBuffers, maxMemory, priority, stackSize)
NDPosPluginConfigure("PANDA02.POS", 1000, 0, "PANDA02.DRV", 0, 0, 0, 0, 0)

# NDFileHDF5Configure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr)
NDFileHDF5Configure("PANDA01.HDF", 1000, 0, "PANDA01.POS", 0)

# NDFileHDF5Configure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr)
NDFileHDF5Configure("PANDA02.HDF", 1000, 0, "PANDA02.POS", 0)

# Final ioc initialisation
# ------------------------
cd "$(TOP)"
dbLoadRecords "$(THIS_DIR)/BL45P-EA-IOC-02_expanded.db"
iocInit
