# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 4.0.1
_src_path: https://github.com/epics-containers/services-template-helm
cluster_name: pollux
cluster_namespace: p45-beamline
cluster_type: dls_cluster
description: p45 IOC Instances and Services
git_platform: github.com
github_org: epics-containers
ioc_group: p45
location: bl45p
logging_url: https://graylog2.diamond.ac.uk/search?rangetype=relative&fields=message%2Csource&width=1489&highlightMessage=&relative=172800&q=pod_name%3A{service_name}*
repo_uri: https://github.com/epics-containers/p45-services

#copier updated