{{- define "ioc-chart.service" -}}

apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-tcp
  annotations:
    metallb.universe.tf/allow-shared-ip: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    beamline: {{ .Values.beamline }}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: ca-tcp
      port: 5064
      targetPort: 5064
      protocol: TCP
  selector:
    app: {{ .Chart.Name }}
---
# TODO - repetition should not be required - look into use of 'range'
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-udp
  annotations:
    metallb.universe.tf/allow-shared-ip: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    beamline: {{ .Values.beamline }}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: ca-udp
      port: 5064
      targetPort: 5064
      protocol: UDP
  selector:
    app: {{ .Chart.Name }}

{{ end }}