# This file was automatically generated on Fri 07 Aug 2020 13:35:28 BST from
# source: /dls_sw/work/R3.14.12.7/support/BL45P-BUILDER/etc/makeIocs/BL45P-MO-IOC-01.xml
#
# *** Please do not edit this file: edit the source file instead. ***
#

# GK Containers Testing April 2021
# builder built IOCs can be converted to containers by dropping their DB and
# startup script in the config folder of the helm chart
#
# changes to boot script required
#    rename to ioc.boot
#    replace all hardcoded root folder with $(TOP)
#    replace references to dbLoadRecords to pass "$(THIS_DIR/dbname)"
#    replace dbLoadDatabase param with dbd/ioc.dbd
#    replace BL45P_MO_IOC_01_registerRecordDeviceDriver with ioc__registerRecordDeviceDriver

cd "$(TOP)"

epicsEnvSet "EPICS_CA_MAX_ARRAY_BYTES", '6000000'
epicsEnvSet "EPICS_TS_MIN_WEST", '0'


# Loading libraries
# -----------------

# Device initialisation
# ---------------------

cd "$(TOP)"

dbLoadDatabase "dbd/ioc.dbd"
ioc_registerRecordDeviceDriver(pdbbase)

# Create IP Port (PortName, IPAddr)
pmacAsynIPConfigure("BRICK1port", "172.23.59.21:1025")

# Configure Model 3 Controller Driver (ControlerPort, LowLevelDriverPort, Address, Axes, MovingPoll, IdlePoll)
pmacCreateController("BRICK1", "BRICK1port", 0, 8, 100, 500)
# Configure Model 3 Axes Driver (Controler Port, Axis Count)
pmacCreateAxes("BRICK1", 8)

pmacDisableLimitsCheck("BRICK1", 3, 0)

pmacDisableLimitsCheck("BRICK1", 4, 0)

pmacDisableLimitsCheck("BRICK1", 5, 0)

# Create CS (CSPortName, ControllerPort, CSNumber, ProgramNumber)
pmacCreateCS("CS1", "BRICK1", 1, 10)
# Configure Model 3 CS Axes Driver (CSPortName, CSAxisCount)
pmacCreateCSAxes("CS1", 9)

# Create CS (CSPortName, ControllerPort, CSNumber, ProgramNumber)
pmacCreateCS("CS2", "BRICK1", 2, 10)
# Configure Model 3 CS Axes Driver (CSPortName, CSAxisCount)
pmacCreateCSAxes("CS2", 9)

pmacCreateCsGroup("BRICK1", 0, "CS1-direct", 9)

pmacCreateCsGroup("BRICK1", 1, "CS2-kinematic", 9)

pmacCsGroupAddAxis(BRICK1, 0, 3, U, 1)

pmacCsGroupAddAxis(BRICK1, 0, 4, A, 1)

pmacCsGroupAddAxis(BRICK1, 0, 5, B, 1)

pmacCsGroupAddAxis(BRICK1, 0, 6, X, 1)

pmacCsGroupAddAxis(BRICK1, 0, 7, Y, 1)

pmacCsGroupAddAxis(BRICK1, 0, 8, Z, 1)

pmacCsGroupAddAxis(BRICK1, 1, 3, U, 1)

pmacCsGroupAddAxis(BRICK1, 1, 4, A, 1)

pmacCsGroupAddAxis(BRICK1, 1, 5, B, 1)

pmacCsGroupAddAxis(BRICK1, 1, 6, I, 2)

pmacCsGroupAddAxis(BRICK1, 1, 7, I, 2)

pmacCsGroupAddAxis(BRICK1, 1, 8, I, 2)

pmacMonitorVariables("BRICK1", "&2Q20 &2Q21 &2Q22")

pmacMonitorVariables("BRICK1", "P4706 P4806 P4906 P4707 P4807 P4907 P4708 P4808 P4908")

# Final ioc initialisation
# ------------------------
cd "$(TOP)"
dbLoadRecords "$(THIS_DIR)/BL45P-MO-IOC-01_expanded.db"
iocInit
