# yaml-language-server: $schema=https://github.com/epics-containers/ioc-adsimdetector/releases/download/2024.6.1/ibek.ioc.schema.json

ioc_name: "{{ _global.get_env('IOC_NAME') }}"

description: Generic instance for testing generic IOCs

entities:
  - type: epics.EpicsEnvSet
    name: EPICS_TZ
    value: "GMT0BST"

  - type: devIocStats.iocAdminSoft
    IOC: "{{ ioc_name | upper }}"

  - type: epics.StartupCommand
    command: dbLoadRecords("/epics/ioc/config/ioc.db")

  - type: epics.PostStartupCommand
    command: |
      dbpf P45:IBEK:A "2.54"
      dbpf P45:IBEK:B "2.61"
      dbgf P45:IBEK:SUM
