# yaml-language-server: $schema=https://github.com/epics-containers/ec-helm-charts/releases/download/4.1.3/ioc-instance.schema.json

ioc-instance:
  image: gcr.io/diamond-privreg/controls/prod/iocs/ioc-dlsvmevac-rtems-beatnik-runtime:2025.1.1b1

  volumeMounts:
    - mountPath: /ioc
      subPath: iocs/bl04i-va-ioc-01
      name: ioc

  startCommand: sleep
  startArgs: infinity

  volumes:
    - name: ioc
      persistentVolumeClaim:
        claimName: p45-binaries-claim

  iocEnv:
    - name: RTEMS_TFTP_PATH
      value: /ioc
