#!/bin/bash

EDMDATAFILES=/screens/bl45p-ea-ioc-02
for i in adpandablocks autosave deviocstats adcore adutil; do
    export EDMDATAFILES=$EDMDATAFILES:/screens/${i}
done

$(dirname ${BASH_SOURCE[0]})/bl45p-launcher.sh BL45P-EA-IOC-02Top.edl ${@}
