# yaml-language-server: $schema=https://github.com/epics-containers/ioc-adaravis/releases/download/2025.8.3/ibek.ioc.schema.json

ioc_name: "[[ _global.get_env('IOC_NAME') ]]"

description: shared template for all Aravis cameras on p45

entities:
  - type: epics.EpicsEnvSet
    name: EPICS_TZ
    value: "GMT0BST"

  - type: epics.EpicsCaMaxArrayBytes
    max_bytes: 6000000

  - type: epics.StartupCommand
    command: callbackSetQueueSize(10000)
    # name: ASYN_CALLBACK_SIZE

  - type: devIocStats.iocAdminSoft
    IOC: "[[ ioc_name | upper ]]"

  - type: ADAravis.aravisCamera
    CLASS: AutoADGenICam
    ID: bl45p-ea-detector-01
    P: BL45P-EA-MAP-01
    PORT: DET.DET
    R: ":DET:"

  - type: ADCore.NDROI
    ADDR: 0
    NDARRAY_ADDR: 0
    NDARRAY_PORT: DET.DET
    P: BL45P-EA-MAP-01
    PORT: DET.roi
    QUEUE: 250
    R: ":ROI:"
    TIMEOUT: 1

  - type: ADCore.NDStats
    ADDR: 0
    HIST_SIZE: 256
    NCHANS: 20000
    NDARRAY_ADDR: 0
    NDARRAY_PORT: DET.DET
    P: BL45P-EA-MAP-01
    PORT: DET.stat
    QUEUE: 250
    R: ":STAT:"
    TIMEOUT: 1
    XSIZE: 1936
    YSIZE: 1216

  - type: ADCore.NDStdArrays
    ADDR: 0
    FTVL: UCHAR
    NDARRAY_ADDR: 0
    NDARRAY_PORT: DET.roi
    NELEMENTS: 2354176
    P: BL45P-EA-MAP-01
    PORT: DET.arr
    QUEUE: 2
    R: ":ARR:"
    TIMEOUT: 1
    TYPE: Int8

  - type: ADCore.NDProcess
    ADDR: 0
    NDARRAY_ADDR: 0
    NDARRAY_PORT: DET.DET
    P: BL45P-EA-MAP-01
    PORT: DET.proc
    QUEUE: 250
    R: ":PROC:"
    TIMEOUT: 1

  # - type: ADCore.NDOverlay
  #   ADDR: 0
  #   NDARRAY_ADDR: 0
  #   NDARRAY_PORT: DET.proc
  #   P: BL45P-EA-MAP-01
  #   PORT: DET.over
  #   QUEUE: 250
  #   R: ":OVER:"
  #   TIMEOUT: 1

  - type: ADCore.NDFileTIFF
    ADDR: 0
    NDARRAY_ADDR: 0
    NDARRAY_PORT: DET.DET
    P: BL45P-EA-MAP-01
    PORT: DET.tiff
    QUEUE: 250
    R: ":TIFF:"
    TIMEOUT: 1

  - type: ADCore.NDFileHDF5
    ADDR: 0
    NDARRAY_ADDR: 0
    NDARRAY_PORT: DET.DET
    P: BL45P-EA-MAP-01
    PORT: DET.hdf
    QUEUE: 250
    R: ":HDF5:"
    TIMEOUT: 1

  # - type: ADCore.NDCircularBuff
  #   NDARRAY_PORT: DET.DET
  #   P: BL45P-EA-MAP-01
  #   PORT: DET.BUFF
  #   R: ":BUFF:"

  - type: ADCore.NDPosPlugin
    ENABLED: 1
    NDARRAY_PORT: DET.DET
    P: BL45P-EA-MAP-01
    PORT: DET.POS
    QUEUE: 1000
    R: ":POS:"

  - type: ADCore.NDPvxsPlugin
    ENABLED: 1
    NDARRAY_PORT: DET.DET
    PVNAME: BL45P-EA-MAP-01:TX:PVA
    PORT: DIFF.PVA
    P: BL45P-EA-MAP-01
    R: ":PVA:"
