# yaml-language-server: $schema=https://github.com/epics-containers/ec-helm-charts/releases/download/4.1.2/ioc-instance.schema.json/#/$defs/service
# shared values for all services

global:
  ioc_group: p45
  location: bl45p
  enabled: true

ioc-instance:
  # useHostNetwork - use host network for IOC - required for Channel Access
  # to work outside of the cluster
  hostNetwork: false
  location: bl45p # TODO remove me when schema is fixed

  # affinity and tolerations to get the right nodes on pollux
  securityContext:
    runAsUser: 1200288
    runAsGroup: 1200288

  dataVolume:
    pvc: false
    hostPath: /dls/p45/data

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: beamline
                operator: In
                values:
                  - bl45p

  tolerations:
    - key: beamline
      operator: Equal
      value: bl45p
      effect: NoSchedule
    - key: location
      operator: Equal
      value: bl45p
      effect: NoSchedule
    - key: nodetype
      operator: Equal
      value: test-rig
      effect: NoSchedule
