# yaml-language-server: $schema=../.helm-shared/values.schema.json
<<<<<<< before updating
=======

>>>>>>> after updating
# shared values for all services

global:
  ioc_group: p45
  location: bl45p
  enabled: true

<<<<<<< before updating
# shared values for both dev-c7 and ioc-instance based charts
shared: &shared
  # useHostNetwork - use host network for IOC - required for Channel Access
  # to work outside of the cluster
  hostNetwork: true

  securityContext:
    allowPrivilegeEscalation: false
    # run as p45detector
    runAsUser: 37988
    runAsGroup: 37988

  # affinity and tolerations to get the right nodes on pollux
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: beamline
                operator: In
                values:
                  - bl45p

  tolerations:
    - key: beamline
      operator: Equal
      value: bl45p
      effect: NoSchedule
    - key: location
      operator: Equal
      value: bl45p
      effect: NoSchedule
    - key: nodetype
      operator: Equal
      value: test-rig
      effect: NoSchedule

dev-c7:
  <<: *shared

  podSecurityContext:
    # run as p45detector
    runAsUser: 37988
    runAsGroup: 37988

ioc-instance:
  <<: *shared

  dataVolume:
    pvc: false
    hostPath: /dls/p45/data

fastcs:
  <<: *shared
=======
# shared settings for all IOC types
shared: &shared
  # hostNetwork
  # set to true for Channel Access work outside of the cluster (or use a gateway)
  hostNetwork: true

  # running as ixxdetector account uid,gid gives access to /dls/ixx/data
  securityContext:
    allowPrivilegeEscalation: false
    # runAsUser: 37988
    # runAsGroup: 37988

  # affinity chooses which servers to run on
  # Accelerator must set this for CIAs, Beamlines don't need it
  affinity:
    {}
    # nodeAffinity:
    #   requiredDuringSchedulingIgnoredDuringExecution:
    #     nodeSelectorTerms:
    #       - matchExpressions:
    #           - key: location
    #             operator: In
    #             values:
    #               - sr03c

  # tolerations allow us to run on a tainted server
  # Accelerator must set this for CIAs, Beamlines don't need it
  tolerations:
    []
    # - key: location
    #   operator: Equal
    #   value: sr03c
    #   effect: NoSchedule

# shared settings for all ibek IOCs using the ioc-instance helm chart
ioc-instance:
  <<: *shared

# shared settings for all fastcs IOCs using the fastcs helm chart
fastcs:
  <<: *shared

# shared setting for all legacy IOCs using the dev-c7 helm chart
dev-c7:
  <<: *shared
>>>>>>> after updating
