# yaml-language-server: $schema=../../.helm-shared/values.schema.json
# shared values for all services

global:
  ioc_group: p45
  location: bl45p
  enabled: true

# shared values for both dev-c7 and ioc-instance based charts
shared: &shared
  # useHostNetwork - use host network for IOC - required for Channel Access
  # to work outside of the cluster
  hostNetwork: false

  securityContext:
    allowPrivilegeEscalation: false
    # runAsUser: 1200288
    # runAsGroup: 1200288

  # affinity and tolerations to get the right nodes on pollux
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: beamline
                operator: In
                values:
                  - bl45p

  tolerations:
    - key: beamline
      operator: Equal
      value: bl45p
      effect: NoSchedule
    - key: location
      operator: Equal
      value: bl45p
      effect: NoSchedule
    - key: nodetype
      operator: Equal
      value: test-rig
      effect: NoSchedule

dev-c7:
  <<: *shared

  podSecurityContext:
    # need to set these for the hgv27681 (giles) namespace to mount in /dls_sw
    runAsUser: 1200288
    runAsGroup: 1200288

ioc-instance:
  <<: *shared

  dataVolume:
    pvc: true
    hostPath: /dls/p45/data
