# shared beamline values for all services

global:
  ioc_group: p45
  location: bl45p
  enabled: true

ioc-instance:
  # useHostNetwork - use host network for IOC - required for Channel Access
  # to work outside of the cluster
  hostNetwork: true

  # affinity and tolerations to get the right nodes on pollux
  securityContext:
    runAsUser: 37988
    runAsGroup: 37988

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: beamline
                operator: In
                values:
                  - bl45p

  tolerations:
    - key: beamline
      operator: Equal
      value: bl45p
      effect: NoSchedule
    - key: location
      operator: Equal
      value: bl45p
      effect: NoSchedule
    - key: nodetype
      operator: Equal
      value: training-rig
      effect: NoSchedule
