# yaml-language-server: $schema=https://github.com/epics-containers/ec-helm-charts/releases/download/4.1.2/ioc-instance.schema.json/#/$defs/service
# shared values for all services

global:
  ioc_group: p45
  location: bl45p
  enabled: true

ioc-instance:
  # useHostNetwork - use host network for IOC - required for Channel Access
  # to work outside of the cluster
  hostNetwork: true
  location: bl45p # TODO remove me when schema is fixed

  # affinity and tolerations to get the right nodes on pollux
  securityContext:
    runAsUser: 37988
    runAsGroup: 37988

  dataVolume:
    pvc: false
    hostPath: /dls/p45/data

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: beamline
                operator: In
                values:
                  - bl45p

  tolerations:
    - key: beamline
      operator: Equal
      value: bl45p
      effect: NoSchedule
    - key: location
      operator: Equal
      value: bl45p
      effect: NoSchedule
    - key: nodetype
      operator: Equal
      value: test-rig
      effect: NoSchedule

  # Common RTEMS settings for all VME Crates for use in rtems-proxy
  globalEnv:
    # # For i04 VME Crates
    # - name: RTEMS_TFTP_PATH
    #   value: /nfsv2-tftp

    # - name: RTEMS_IOC_GATEWAY
    #   value: 172.23.104.254

    # - name: RTEMS_IOC_NETMASK
    #   value: 255.255.240.0

    # - name: RTEMS_NFS_IP
    #   value: 172.23.104.224

    # - name: RTEMS_TFTP_IP
    #   value: 172.23.104.224

    # For testing on the Controls Dev Network Crates
    - name: RTEMS_TFTP_PATH
      value: /nfsv2-tftp

    - name: RTEMS_IOC_GATEWAY
      value: 172.23.104.254

    - name: RTEMS_IOC_NETMASK
      value: 255.255.240.0

    - name: RTEMS_NFS_IP
      value: 172.23.168.190

    - name: RTEMS_TFTP_IP
      value: 172.23.168.190
