# yaml-language-server: $schema=schema.json

# a temporary configuration file for running in the cluster - this will be provided
# by the helm chart eventually

# EXAMPLE CONTROLLER CONFIGURATION YAML REPLACE WITH YOURS

controller:
  ip_settings:
    ip: "localhost"
    port: 25565
  num_ramp_controllers: 1
transport:
  - pva_ioc:
      pv_prefix: P45-EA-FASTCS-01
    gui:
      output_path: /epics/opi/pva_example.bob
  - ca_ioc:
      pv_prefix: P45-EA-FASTCS-01
    gui:
      output_path: /epics/opi/ca_example.bob
