# IOC volume
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ioc-nfsv2-tftp-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
# Autosave volume
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: autosave-volume-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nfstftpserver
  labels:
    app: nfstftpserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfstftpserver
  template:
    metadata:
      labels:
        app: nfstftpserver
    spec:
      volumes:
        - name: ioc-nfsv2-tftp-volume
          persistentVolumeClaim:
            claimName: ioc-nfsv2-tftp-claim
        - name: autosave-volume
          persistentVolumeClaim:
            claimName: autosave-volume-claim
      containers:
        - name: server
          image: {{ .Values.image }}
          resources:
            requests:
              memory: "512Mi"
              cpu: "1"
            limits:
              memory: "1Gi"
              cpu: "2"
          ports:
            - containerPort: 2049
              protocol: UDP
            - containerPort: 20048
              protocol: UDP
            - containerPort: 111
              protocol: UDP
            - containerPort: 69
              protocol: UDP
          volumeMounts:
            - mountPath: "/iocs"
              name: ioc-nfsv2-tftp-volume
            - mountPath: "/autosave"
              name: autosave-volume
          securityContext:
            capabilities:
                drop: [NET_RAW]

---
kind: Service
apiVersion: v1
metadata:
  name: nfstftpserver
  labels:
    app: nfstftpserver
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: rpcbind
      port: 111
      protocol: UDP
      targetPort: 111
    - name: nfsd
      port: 2049
      protocol: UDP
      targetPort: 2049
    - name: mountd
      port: 20048
      protocol: UDP
      targetPort: 20048
    - name: tftp
      port: 69
      protocol: UDP
      targetPort: 69
  sessionAffinity: None
  selector:
    app: nfstftpserver
  loadBalancerIP: "{{ .Values.loadBalancerIP }}"

---
# Pod as a target for kubectl cp commands
# to put them in the volume.
kind: Deployment
apiVersion: apps/v1
metadata:
  name: file-transfer-station
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-transfer-station
  template:
    metadata:
      labels:
        app: file-transfer-station
    spec:
      volumes:
        - name: ioc-nfsv2-tftp-volume
          persistentVolumeClaim:
            claimName: ioc-nfsv2-tftp-claim
        - name: autosave-volume
          persistentVolumeClaim:
            claimName: autosave-volume-claim
      containers:
        - name: file-transfer-station
          image: debian:latest
          command: ["/bin/sleep"]
          args: ["infinity"]

          resources:
            requests:
              memory: "512Mi"
              cpu: "1"
            limits:
              memory: "1Gi"
              cpu: "2"
          volumeMounts:
            - mountPath: "/iocs"
              name: ioc-nfsv2-tftp-volume
            - mountPath: "/autosave"
              name: autosave-volume
