# Arguments to the shared ioc instance template dls-aravis
# This will make an IOC instance for an aravis camera with a standard set
# of Areadetector plugins.

dls-aravis:
  P: BL45P-EA-DIFF-01
  ID: bl45p-ea-detector-02

ioc-instance:
  image: ghcr.io/epics-containers/ioc-adaravis-runtime:2024.11.1
