# This file was automatically generated on Tue 01 Jun 2021 07:43:42 BST from
# source: /scratch/work/bl45p-builder/etc/makeIocs/BL45P-EA-IOC-05.xml
#
# *** Please do not edit this file: edit the source file instead. ***
#
cd "$(TOP)"

epicsEnvSet "EPICS_TS_MIN_WEST", '0'


# Loading libraries
# -----------------

# Device initialisation
# ---------------------

cd "$(TOP)"

dbLoadDatabase "dbd/ioc.dbd"
ioc_registerRecordDeviceDriver(pdbbase)

# simDetectorConfig(portName, maxSizeX, maxSizeY, dataType, maxBuffers, maxMemory)
simDetectorConfig("AND.CAM", 4128, 4104, 1, 50, 0)

# Autosave and restore initialisation
set_requestfile_path "$(TOP)/"'data'
set_savefile_path "/autosave"

save_restoreSet_status_prefix "BL45P-EA-IOC-05"
save_restoreSet_Debug 0
save_restoreSet_NumSeqFiles 3
save_restoreSet_SeqPeriodInSeconds 600
save_restoreSet_DatedBackupFiles 1
save_restoreSet_IncompleteSetsOk 1
set_pass0_restoreFile "BL45P-EA-IOC-05_0.sav"
set_pass0_restoreFile "BL45P-EA-IOC-05_1.sav"
set_pass1_restoreFile "BL45P-EA-IOC-05_1.sav"
set_pass1_restoreFile "BL45P-EA-IOC-05_2.sav"

# KafkaPluginConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxMemory, brokerAddress, topic)
KafkaPluginConfigure("ANDK", 3, 1, "AND.CAM", 0, -1, cs05r-sc-cloud-19.diamond.ac.uk:30016, and_topic)

# Final ioc initialisation
# ------------------------
cd "$(TOP)"
dbLoadRecords "$(THIS_DIR)/BL45P-EA-IOC-05_expanded.db"
iocInit

create_monitor_set "BL45P-EA-IOC-05_0.req",  5, ""
create_monitor_set "BL45P-EA-IOC-05_1.req", 30, ""
create_monitor_set "BL45P-EA-IOC-05_2.req", 30, ""

dbpf "BL45P-EA-AND-01:KFK:EnableCallbacks", "Enable"
dbpf "BL45P-EA-AND-01:KFK:KafkaMaxQueueSize", "50"

dbpf "BL45P-EA-AND-01:CAM:ImageMode",  "Multiple"
dbpf "BL45P-EA-AND-01:CAM:NumImages", "1000"
dbpf "BL45P-EA-AND-01:CAM:AcquirePeriod", ".02"
