# yaml-language-server: $schema=https://github.com/marcelldls/ec-helm-charts/releases/download/3.4.4/ioc-instance.schema.json#/$defs/service

# latest container image for the pmac motion controller
ioc-instance:
  image: ghcr.io/epics-containers/ioc-pmac-runtime:2024.9.1
