# A Helm Chart for an IOC instance
apiVersion: v2
name: ec-service
version: 1.0.0

type: application

dependencies:
  - name: ioc-instance
    version: 4.1.2
    repository: "oci://ghcr.io/epics-containers"
