# yaml-language-server: $schema=../../.helm-shared/values.schema.json

ioc-instance:
  image: ghcr.io/diamondlightsource/fastcs-example:2025.10.1

  args:
    - stdio-socket --ptty "fastcs-example run /epics/ioc/config/controller.yaml"

  extraContainers:
    - name: temp-controller-simulator
      image: ghcr.io/diamondlightsource/fastcs-example:2025.10.1
      command:
        - tickit
        - all
        - /epics/ioc/config/temp_controller.yaml

  # don't use the ioc-instance livenesProbe, preStop which dont exist in fastcs image.
  livenessExecutable: ""
  preStopExecutable: ""
