blueapi:
  hostNetwork: true
  resources:
    limits:
      cpu: 1000m
      memory: 500Mi
    requests:
      cpu: 500m
      memory: 100Mi
  nodeSelector:
    kubernetes.io/hostname: p45-control.diamond.ac.uk
  tolerations:
  - key: nodetype
    operator: Equal
    value: test-rig
    effect: NoSchedule
  - key: beamline
    operator: Equal
    value: bl45p
    effect: NoSchedule
  ingress:
    create: true
    host: p45-blueapi.diamond.ac.uk
  extraEnvVars:
  - name: RABBITMQ_PASSWORD
    valueFrom:
      secretKeyRef:
        name: rabbitmq-password
        key: rabbitmq-password
  worker:
    env:
      sources:
      - kind: dodal
        module: dodal.beamlines.p45
      - kind: planFunctions
        module: i22_bluesky.plans
        # TODO: Make p45 plans repository
      - kind: planFunctions
        module: dls_bluesky_core.plans
      - kind: planFunctions
        module: dls_bluesky_core.stubs
      events:
        broadcast_status_events: False
    stomp:
      auth:
        username: p45
        password: ${RABBITMQ_PASSWORD}
      host: p45-rabbitmq-daq.diamond.ac.uk
    scratch:
      root: /dls_sw/p45/software/blueapi/scratch

  initContainer:
    scratch:
      root: /dls_sw/p45/software/blueapi/scratch
      repositories:
      - name: dodal
        remote_url: https://github.com/DiamondLightSource/dodal.git
      - name: i22-bluesky
        remote_url: https://github.com/DiamondLightSource/i22-bluesky.git
  scratchHostPath: /dls_sw/p45/software/blueapi/scratch
